# Generated by Django 3.1.7 on 2023-11-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_auto_20231109_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='materials_provided',
        ),
        migrations.AddField(
            model_name='student',
            name='materials_provide',
            field=models.ManyToManyField(to='storeapp.Material'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('Commerce', 'Commerce'), ('Science', 'Science'), ('Arts', 'Arts'), ('Engineering', 'Engineering'), ('Medicine', 'Medicine')], max_length=20),
        ),
    ]
