# Generated by Django 3.1.7 on 2023-11-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_auto_20231109_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='materials_provide',
            field=models.ManyToManyField(blank=True, to='storeapp.Material'),
        ),
    ]
