# Generated by Django 3.1.7 on 2023-11-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0007_auto_20231109_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[], default='BCA', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('Commerce', 'Commerce'), ('Science', 'Science'), ('Arts', 'Arts'), ('Engineering', 'Engineering'), ('Medicine', 'Medicine')], default='Science', max_length=20),
        ),
    ]
