# Generated by Django 3.1.7 on 2023-11-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0008_auto_20231109_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[], default='Biology', max_length=20),
        ),
    ]
