# Generated by Django 4.2.7 on 2023-11-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0010_auto_20231109_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[], default='Biology', max_length=20),
        ),
    ]
