# Generated by Django 4.2.7 on 2023-11-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0012_remove_student_course_remove_student_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='purpose',
            field=models.CharField(choices=[('Enquiry', 'Enquiry'), ('Place Order', 'Place Order'), ('Return', 'Return')], default='Enquiry', max_length=20),
        ),
    ]
